services:
  mongo:
    image: mongo:latest
    container_name: plate-id-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pl4t31D
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
